// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfSznlqZ7eYnemiJczvs4LrIg_8hOWMLc',
    appId: '1:1014929579030:web:3883b52fde89003a136937',
    messagingSenderId: '1014929579030',
    projectId: 'tuneupedu',
    authDomain: 'tuneupedu.firebaseapp.com',
    storageBucket: 'tuneupedu.firebasestorage.app',
    measurementId: 'G-NDVCQBPRK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsCRqHZ1k6j46SjFaKjjPC_Jm7SfLnErk',
    appId: '1:1014929579030:android:3df0dd4017cc16ec136937',
    messagingSenderId: '1014929579030',
    projectId: 'tuneupedu',
    storageBucket: 'tuneupedu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqjuZveVbn9-8-yGyKleKoVr0NtVt52t0',
    appId: '1:1014929579030:ios:126ed52729c051a6136937',
    messagingSenderId: '1014929579030',
    projectId: 'tuneupedu',
    storageBucket: 'tuneupedu.firebasestorage.app',
    iosBundleId: 'com.tuneup.edu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqjuZveVbn9-8-yGyKleKoVr0NtVt52t0',
    appId: '1:1014929579030:ios:126ed52729c051a6136937',
    messagingSenderId: '1014929579030',
    projectId: 'tuneupedu',
    storageBucket: 'tuneupedu.firebasestorage.app',
    iosBundleId: 'com.tuneup.edu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfSznlqZ7eYnemiJczvs4LrIg_8hOWMLc',
    appId: '1:1014929579030:web:9e010f1f39b9e0cf136937',
    messagingSenderId: '1014929579030',
    projectId: 'tuneupedu',
    authDomain: 'tuneupedu.firebaseapp.com',
    storageBucket: 'tuneupedu.firebasestorage.app',
    measurementId: 'G-YG3DXJH03M',
  );
}
